[package]
name = "staturs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "staturs-signals"
path = "bin/signals.rs"

[[bin]]
name = "staturs-sensors"
path = "bin/sensors.rs"

[[bin]]
name = "staturs-ipc"
path = "bin/ipc.rs"

[dependencies]
async-stream = "0.3.5"
async-trait = "0.1.68"
bytesize = { version = "1.2.0", features = ["serde"] }
chrono = "0.4.24"
clap = { version = "4.2.7", features = ["derive"] }
dbus = { version = "0.9.7", features = ["futures"] }
dbus-tokio = "0.7.6"
dirs = "5.0.1"
figment = { version = "0.10.8", features = ["toml", "yaml", "json"] }
futures = "0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
hex_color = { version = "2.0.0", features = ["serde"] }
humantime-serde = "1.1.1"
iwlib = "0.1.0"
libc = "0.2.142"
libpulse-binding = { version = "2.27.1", features = ["pa_v14"] }
libpulse-tokio = "0.1.0"
log = "0.4.17"
nix = { version = "0.26.2", features = ["net"] }
num-traits = "0.2.15"
paste = "1.0.12"
pretty_env_logger = "0.4.0"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
serde_repr = "0.1.12"
signal-hook = "0.3.15"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
strum = { version = "0.24.1", features = ["derive"] }
sysinfo = { version = "0.28.4", default-features = false }
tokio = { version = "1.27.0", features = ["full"] }
