[package]
name = "staturs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.5"
async-trait = "0.1.68"
automod = "1.0.8"
bytesize = "1.2.0"
chrono = "0.4.24"
dbus = { version = "0.9.7", features = ["futures"] }
dbus-tokio = "0.7.6"
futures = "0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
hex_color = { version = "2.0.0", features = ["serde"] }
libc = "0.2.142"
libpulse-binding = { version = "2.27.1", features = ["pa_v14"] }
nix = { version = "0.26.2", features = ["net"] }
paste = "1.0.12"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
serde_repr = "0.1.12"
sysinfo = "0.28.4"
tokio = { version = "1.27.0", features = ["full"] }
