# This file was included from main configuration file.

# Example of adding an additional item in the middle of an existing bar configuration.
[[items]]
type = "raw"
# Specifying the index so we can insert this item in the already defined list of
# items from the parent configuration file.
index = 7
full_text = "hello"
color = "#000000"
background = "#aaaa00"

# Example of updating the theme.
[theme]
powerline_enable = true
