[[items]]
type = "net_usage"
interval = "1s"
# anything under this threshold will show as "-"
minimum = "1 kiB"
# 5 levels:
#     0..1st: grey
#   1st..2nd: normal
#   2nd..3rd: yellow
#   3rd..4th: orange
#   4th..5th: red
#   5th..MAX: purple
thresholds = ["1kiB", "1MiB", "10MiB", "25MiB", "100MiB"]

[[items]]
type = "nic"
interval = "60s"

[[items]]
type = "disk"
interval = "60s"

[[items]]
type = "cpu"
interval = "2s"
pad = '0'
pad_count = 2

[[items]]
type = "sensors"
interval = "5s"
label = "coretemp Package id 0"

[[items]]
type = "mem"
interval = "10s"

[[items]]
type = "pulse"
max_volume = 120

[[items]]
type = "battery"
interval = "10s"
batteries = ["/sys/class/power_supply/BAT0"]

[[items]]
type = "kbd"
show = ["caps_lock", "num_lock"]
signal = 4

[[items]]
type = "time"
format_long = "%Y-%m-%d %H:%M:%S"
format_short = "%H:%M"
interval = "1s"

[[items]]
type = "script"
command = "echo -n `if [ ! -z $I3_BUTTON ]; then echo button=$I3_BUTTON; else echo bar item; fi`"

[[items]]
type = "script"
command = """ echo -n '{"full_text":"<span foreground=\\"orange\\">G'"'"'day</span>"}' """
output = "json"
markup = "pango"

[[items]]
type = "dunst"
