# TODO: a nice config format

[[items]]
type = "net_usage"

[[items]]
type = "nic"

[[items]]
type = "disk"

[[items]]
type = "cpu"

[[items]]
type = "sensors"

[[items]]
type = "mem"

[[items]]
type = "pulse"

[[items]]
type = "battery"

[[items]]
type = "kbd"

[[items]]
type = "time"

[[items]]
type = "script"
command = "echo -n `if [ ! -z $I3_BUTTON ]; then echo button=$I3_BUTTON; else echo bar item; fi`"
output = "simple"

[[items]]
type = "script"
command = """ echo -n '{"full_text":"<span foreground=\\"orange\\">G'"'"'day</span>"}' """
output = "json"
markup = "pango"

[[items]]
type = "dunst"
