on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3
      # install just
      - uses: extractions/setup-just@v1
      # setup rust toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - run: rustup show

      - run: just setup
      - run: just build
      - run: DEBUG=true just test

  # TODO: build and upload to release tag
