on:
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "master", "next" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3
      # install just
      - uses: extractions/setup-just@v1
      # setup rust toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - run: rustup show
      # cache
      - uses: actions/cache@v3
        with:
          path: scripts/node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # verify
      - run: just setup
      - run: just build
      - run: DEBUG=1 just test

  release-aur-git:
    name: Update AUR(i3stat-git)
    needs: ['verify']
    runs-on: ubuntu-latest
    # this should only run on pushes to `next`, not pull requests to it
    if: github.event_name == 'push'
    steps:
      - uses: extractions/setup-just@v1
      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
          ssh-add - <<< "${{ secrets.AUR_SSH_KEY }}"
          mkdir -p $HOME/.ssh/
          echo "${{ vars.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
          chmod 0600 $HOME/.ssh/*
      - run: |
          git clone ssh://aur@aur.archlinux.org/i3stat-git.git i3stat && cd "$_"
          docker run \
            --rm \
            -v "$PWD:/pkg" \
            --user "$(id -u)" \
            --env "GIT_AUTHOR_NAME=acheronfail" \
            --env "GIT_COMMITTER_NAME=acheronfail" \
            --env "GIT_AUTHOR_EMAIL=acheronfail@gmail.com" \
            --env "GIT_COMMITTER_EMAIL=acheronfail@gmail.com" \
            acheronfail/makepkg just update
          git push
