name: Verify

on:
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runs-on: buildjet-4vcpu-ubuntu-2204-arm
    name: Build & Test
    runs-on: ${{ matrix.runs-on }}
    steps:
      # git checkout
      - uses: actions/checkout@v3
      # install just
      - uses: extractions/setup-just@v1
      # setup rust toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - run: rustup show && rustup target add ${{ matrix.target }}
      # cache
      - uses: actions/cache@v3
        with:
          path: scripts/node/node_modules
          key: ${{ runner.runs-on }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target/
          key: ${{ runner.runs-on }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      # verify
      - run: just setup
      - run: just build
      - run: DEBUG=1 just test

  release-aur-git:
    name: Update AUR(i3stat-git)
    needs: ['verify']
    runs-on: ubuntu-latest
    # this should only run on pushes to `next`, not pull requests to it
    if: github.event_name == 'push'
    steps:
      - uses: extractions/setup-just@v1
      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
          ssh-add - <<< "${{ secrets.AUR_SSH_KEY }}"
          mkdir -p $HOME/.ssh/
          echo "${{ vars.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
          chmod 0600 $HOME/.ssh/*
      - run: |
          git clone ssh://aur@aur.archlinux.org/i3stat-git.git aur && cd "$_" && git checkout master
          sudo chown -R 1000:1000 "$PWD"
          docker run \
            --rm \
            -v "$PWD:/pkg" \
            --env "GIT_AUTHOR_NAME=acheronfail" \
            --env "GIT_COMMITTER_NAME=acheronfail" \
            --env "GIT_AUTHOR_EMAIL=acheronfail@gmail.com" \
            --env "GIT_COMMITTER_EMAIL=acheronfail@gmail.com" \
            acheronfail/makepkg just update
          sudo chown -R $USER:$USER "$PWD"
          git push
