on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3
      # install just
      - uses: extractions/setup-just@v1
      # setup rust toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - run: rustup show
      # cache
      - uses: actions/cache@v3
        with:
          path: scripts/node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: target/
          key: ${{ runner.os }}-cargo

      # verify
      - run: just setup
      - run: just build
      - run: DEBUG=1 just test
